### ISSUE TITLE
Feature Request - Implement Version Checking and Node Bans for old versions

### ISSUE THREAD

**Issue by 0xDEADBEEF-td** [SemkoDev/field.cli#12]
With the issues people are reporting with light wallet and Trinity Beta while using field, node/IP ban should be implemented if ping-back reports back an old version, and message should be logged in local field logs that upgrade is required.

Possibly require or have an option of node operator email address as a startup flag for field, allowing notification to node operator that field upgrade is required if node wishes to continue to be part of field solution.

**Comment by romansemko** [comment]
Added semver checking and set currently to 0.1.3

Thanks for the idea!
