### ISSUE TITLE
CORS in header

### ISSUE THREAD

**Issue by cyclux** [SemkoDev/field.cli#13]
As mentioned on Discord, would be nice to have `Access-Control-Allow-Origin: *` in the header for some usecases.

`X-IOTA-API-Version` and `Content-Type` are also in the `Access-Control-Request-Headers` of the library.
As reference here the headers from `http://nodes.iota.fm/` Balaner:
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, X-IOTA-API-Version
```

**Comment by romansemko** [comment]
CORS has been added.
