### ISSUE TITLE
Add a little more security

### ISSUE THREAD

**Issue by ds2216** [SemkoDev/field.cli#15]
Add security by publishing IP-Address(es) or DNS-Name(s) that will contact field clients. Node operators can then configure there firewall to only accept incoming connections from those addresses instead of opening the configured port (default 21310) for the whole internet (including the bad boys).

**Comment by romansemko** [comment]
Field drops any request that comes from a non-field server. The Field server runs on an auto-scalable infrastructure in multiple zones, which has many, many IP ranges. If I provided such a list, it would be inaccurate and probably outdated within days.

**Comment by ds2216** [comment]
Ok, so you already have some security built in higher level.
