### ISSUE TITLE
"Ping back to client IP failed: [ipaddress]

### ISSUE THREAD

**Issue by Nick2bad4u** [SemkoDev/field.cli#17]
[![Screenshot from Gyazo](https://gyazo.com/1d69da27a69c511b34f5ed84e6b6c02b/raw)](https://gyazo.com/1d69da27a69c511b34f5ed84e6b6c02b)

1|field    |     at Object._errnoException (util.js:1003:13)
1|field    |     at _exceptionWithHostPort (util.js:1024:20)
1|field    |     at Server.setupListenHandle [as _listen2] (net.js:1367:14)
1|field    |     at listenInCluster (net.js:1408:12)
1|field    |     at Server.listen (net.js:1496:7)
1|field    |     at Proxy.listen (/usr/lib/node_modules/field.cli/node_modules/hoxy/lib/proxy.js:417:27)
1|field    |     at Field.start (/usr/lib/node_modules/field.cli/dist/field.js:112:10)
1|field    |     at Object.<anonymous> (/usr/lib/node_modules/field.cli/dist/index.js:40:7)
1|field    |     at Module._compile (module.js:660:30)
1|field    |     at Object.Module._extensions..js (module.js:671:10)
1|field    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|field    | Error: connect ECONNREFUSED 127.0.0.1:14265
1|field    |     at Object._errnoException (util.js:1003:13)
1|field    |     at _exceptionWithHostPort (util.js:1024:20)
1|field    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)

1|field    | 14:33:56.290       FIELD        Field Client v.0.1.5
1|field    | 14:33:56.512       FIELD        Field ID: 7419ca51b1b36415XXXXXXXXXXXXX
1|field    | 14:33:56.513       FIELD        Public ID: 7419ca51b1b36415
1|field    | 14:33:56.734       FIELD        IRI online!

1|field    | 14:34:16.794       FIELD        Field update error to field.carriota.com: 429 null { error: 'IP flagged for 5 minutes due to misbehaviour: Ping back to Client IP failed: 208.115.1                                    04.145' }
1|field    | 14:34:36.880       FIELD        Field update error to field.carriota.com: 429 null { error: 'IP flagged for 5 minutes due to misbehaviour: Ping back to Client IP failed: 208.115.1                                    04.145' }
1|field    | 14:34:56.803       FIELD        Field update error to field.carriota.com: 429 null { error: 'IP flagged for 5 minutes due to misbehaviour: Ping back to Client IP failed: 208.115.1                                    04.145' }

I run 12 nodes, and this has been happening to about 3-4 of them. Sometimes a restart of Field fixes the issue, sometimes a full restart is required. Sometimes the error occurs and it causes no issues.

[![Screenshot from Gyazo](https://gyazo.com/6fdbca2dc9c7461e63589568526724a4/raw)](https://gyazo.com/6fdbca2dc9c7461e63589568526724a4)

Ping obviously works, tested from my home computer to my VPS.

**Comment by romansemko** [comment]
I removed your FieldID from your bug description. Please never share it.

**Comment by romansemko** [comment]
I increased the pingback timeout on the field server. This should solve the issue, unless the connection gets slow for some reason. In that case, this is a correct behaviour.

**Comment by JonasMock** [comment]
@romansemko In which configuration file did you increase the pingback timeout ? I have the same issue.

**Comment by PippoAe** [comment]
Having the same problem.
Can ping my IP fine from my mobile-phone.
@romansemko In which configuration file did you increase the pingback timeout ? I have the same issue.
