### ISSUE TITLE
Field's name and address info are incorrect on node graph explorer

### ISSUE THREAD

**Issue by yaeljiao** [SemkoDev/field.cli#26]
My field's config.ini is shown as below: 
```
[field]
name =[CN]Jiao
IRIPort = 14265
IRIHostname = localhost
address = YVIVYCSRJVP9JBOLZ9LGMMKSXMYIFNGWIODVDQPZMCJJNRXDZCLMVSTUSWHNPWGYOOEQNP9MTKOYRMTFYKQSSAJNNY
port = 21310
pow = true
disableIRI = false
```

I checked my node's info on http://field.carriota.com/api/v1/graph:
```
{
  "createdOn": "2018-02-28T01:26:47.047Z",
  "iri": {
    "appVersion": "1.4.2.2",
    "latestMilestoneIndex": 359379,
    "latestSolidSubtangleMilestoneIndex": 359379,
    "isSynchronized": true
  },
  "field": {
    "publicId": "3053677ad6a58903",
    "version": "0.1.5",
    "name": "CarrIOTA Field Node #3053677ad6a58903",
    "disableIRI": false,
    "pow": false,
    "address": null
  },
  "neighbors": [
    "76e667cf838e3134",
    "62b4fbf76d184af8",
    "534f14307e08a886"
  ],
  "workDone": {
    "getInclusionStates": 23,
    "wereAddressesSpentFrom": 9,
    "findTransactions": 7,
    "getNodeInfo": 17,
    "getBalances": 1,
    "getTrytes": 54
  },
  "you": false
}
```

My field's name is marked as `"CarrIOTA Field Node #3053677ad6a58903"` and address is `null`
It seems that the information is not correct.

**Comment by romansemko** [comment]
Try running your field with "customFieldId = true". It seems that another server has the same machine id (Image-based server)

**Comment by yaeljiao** [comment]
I tried "customFieldId = true", but it's not working for this issue. Any other suggestion? I'm using Google Cloud for deployment.

**Comment by New-older** [comment]
I had the same problem in the past. Please see my fixing flow as below:
1. create a new config.ini
 nano /lib/systemd/system/config.ini
2. changed the path of config.ini in the field.ini
 nano /lib/systemd/system/field.service
ExecStart=/usr/bin/field –config /lib/systemd/system/config.ini
3. systemctl restart field.service or reboot

wo de yijing hao le . yong xin zhongzi is best way.

**Comment by romansemko** [comment]
@yaeljiao Did it solve your issue?

**Comment by yaeljiao** [comment]
Yes, @New-older 's comments solved  my issue
