### ISSUE TITLE
field.carriota.com over https is not usable

### ISSUE THREAD

**Issue by Xermio** [SemkoDev/field.cli#27]
`lodash.js:9701 Mixed Content: The page at 'https://field.carriota.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://field.carriota.com:50882/'. This endpoint should be available via WSS. Insecure access is deprecated.`

`Connecting to a non-secure WebSocket server from a secure origin is deprecated.`

Testet browsers: Opera, Chrome, Vivaldi, Edge and Firefox; latest versions.

**Comment by m1ndgames** [comment]
Related: https://github.com/SemkoDev/field.cli/issues/25

**Comment by romansemko** [comment]
This should be fixed now.
