### ISSUE TITLE
Some clients are using the same "id"

### ISSUE THREAD

**Issue by Xermio** [SemkoDev/field.cli#3]
Because some servers are running with the same baseimage, these machines do have the same machine-id.

https://www.npmjs.com/package/node-machine-id

Take a look at "Caveats" at the bottom of the page.

**Comment by romansemko** [comment]
Added the caveat to the README. Thanks for pointing out!

**Comment by glumb** [comment]
I am not sure if its a good idea to advise people to change their machine-id. Especially without a word of warning.

Why not generate some ID file `.fiels_cli_id.txt`, create a unique hash/ID on first execution and read it on successive program starts?

**Comment by glumb** [comment]
Is the MAC adresse sufficient for creating an id?

**Comment by Xermio** [comment]
When you cloning a virtual machine these do have the same MAC, if not changed while cloning. (As example)

Best (and maybe only "safe") way is to use a random id.

**Comment by ioiobzit** [comment]
Hi, I'm using docker images, and this images do not contain the ```/var/lib/dbus/machine-id``` or ```dbus-uuidgen``` therefore the ID cannot be created/renewed.

Any ideas?

**Comment by romansemko** [comment]
do you have /etc/machine-id ?

**Comment by ioiobzit** [comment]
does not look like it is there:

```
/usr/src/field # ls /etc/

TZ               init.d/          network/         securetty
alpine-release   inittab          opt/             services
apk/             issue            os-release       shadow
conf.d/          localtime        passwd           shadow-
crontabs/        logrotate.d/     passwd-          shells
fstab            modprobe.d/      periodic/        ssl/
group            modules          profile          sysctl.conf
group-           modules-load.d/  profile.d/       sysctl.d/
hostname         motd             protocols        udhcpd.conf
hosts            mtab             resolv.conf
```

**Comment by MatthiasLohr** [comment]
The problem exists also with docker images,

@romansemko, what's the reason for avoiding it?

**Comment by romansemko** [comment]
Will add optional custom machine ID generation.
