### ISSUE TITLE
Error 429 "ip flagged for 5 minutes due to misbehaviour #1"

### ISSUE THREAD

**Issue by Xermio** [SemkoDev/field.cli#8]
Without any recognizable reason my IP got flagged "due to misbehaviour # 1".

Other users do also have the problem.

Logfile:
[field.error.log](https://github.com/SemkoDev/field.cli/files/1716951/field.error.log)

**Comment by VvanGemert** [comment]
Got the same. Trying field.cli with IRI 1.4.2.1 and Nelson 0.4.0.

**Comment by 0xDEADBEEF-td** [comment]
Same issue. Running 3 different IRI 1.4.2.1 + Nelson 0.4.0 behind same external IP on different ports. field.cli version 0.1.3

**Comment by romansemko** [comment]
Can you confirm that your port 21310 is open?

**Comment by Xermio** [comment]
21310/tcp open

The error happens more often, when you run multiple Field clients with the same ip.

Error 429 --> "Too Many Requests"

**Comment by VvanGemert** [comment]
Sorry my bad. I've opened the UDP port instead of TCP, while copying iptable lines. It's working now for me.

**Comment by romansemko** [comment]
There are only two cases, when the node would be flagged:
1. Ping-back to source.ip:21310 failed. The port is probably closed or firewalled.
2. Several nodes with different machine-ids are running on same source-ip
Both are to prevent different nodes running on same IP or flooding the server with false data.

**Comment by romansemko** [comment]
@0xDEADBEEF-td your problem seems related to the fact, that you run multiple nodes behind same IP. This is not supported.

**Comment by romansemko** [comment]
Closing as the explanation seems to affect most of the reported behaviour. Please open a new ticket, if the problem should persist.
