### ISSUE TITLE
HTTP 400 Being Recieved during field ping

### ISSUE THREAD

**Issue by 0xDEADBEEF-td** [SemkoDev/field.cli#9]
Experiencing HTTP 400 "Command.[undefined].is.unknown" during node pings from field servers, can this be cleaned up?

[field-tcpdump.txt](https://github.com/SemkoDev/field.cli/files/1725111/field-tcpdump.txt)

tcpdump output is attached

**Comment by romansemko** [comment]
Thanks! Will be fixed.

**Comment by romansemko** [comment]
Done.
